config: hz: Fix compilation overflow error with 12HZ
The error is as follows:
```
In file included from ./include/linux/jiffies.h:12,
                 from ./include/linux/ktime.h:25,
                 from ./include/linux/timer.h:6,
                 from ./include/linux/clocksource.h:17,
                 from kernel/time/jiffies.c:7:
./include/vdso/jiffies.h:9:19: error: unsigned conversion from 'long int' to 'unsigned int' changes value from '5333333312' to '1038366016' [-Werror=overflow]
    9 | #define TICK_NSEC ((NSEC_PER_SEC+HZ/2)/HZ)
      |                   ^
kernel/time/jiffies.c:38:35: note: in expansion of macro 'TICK_NSEC'
   38 |         .mult                   = TICK_NSEC << JIFFIES_SHIFT, /* details above */
      |                                   ^~~~~~~~~
```

When HZ is less than 30, JIFFIES_SHIFT needs to be reduced to 5, otherwise it will cause u32 overflow, because the data type of 'struct clocksource.mult' is u32.

Signed-off-by: hanyu.cp <hanyu.cp@alibaba-inc.com>
Change-Id: I537a254f68a8a77c08bf0a74d1cc8ace47c7febf